# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'change_username_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 250)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        Dialog.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("main_icon/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("QLabel{\n"
"    color:#292828;\n"
"    margin-bottom:5;\n"
"}\n"
"QLineEdit{\n"
"    padding-left:5;\n"
"    margin:5;\n"
"    color: white;\n"
"    background-color:#292828;\n"
"    selection-background-color:white;\n"
"    selection-color:#292828;\n"
"    border-radius:10;\n"
"\n"
"}\n"
"QDialog{\n"
"    background-color:white;\n"
"}\n"
"QPushButton{\n"
"    outline:none;\n"
"    margin:5;\n"
"    color:white;\n"
"    background-color:#292828;\n"
"    border-radius:10;\n"
"    border-style:outset;\n"
"}\n"
"QPushButton:pressed{\n"
"    margin:5;\n"
"    color:#292828;\n"
"    background-color:white;\n"
"    border-style:inset;\n"
"    border-color:#292828;\n"
"    border-width:1;\n"
"}<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
"<ui version=\"4.0\">\n"
" <widget name=\"__qt_fake_top_level\">\n"
"  <widget class=\"QPushButton\" name=\"pushButton\">\n"
"   <property name=\"geometry\">\n"
"    <rect>\n"
"     <x>530</x>\n"
"     <y>370</y>\n"
"     <width>75</width>\n"
"     <height>31</height>\n"
"    </rect>\n"
"   </property>\n"
"   <property name=\"styleSheet\">\n"
"    <string notr=\"true\">QPushButton#pushButton{\n"
"    margin:5;\n"
"    color:white;\n"
"    background-color:#292828;\n"
"    border-radius:10;\n"
"    border-style:outset;\n"
"}\n"
"QPushButton#pushButton:pressed{\n"
"    margin:5;\n"
"    background-color:black;\n"
"    border-style:inset;\n"
"}</string>\n"
"   </property>\n"
"   <property name=\"text\">\n"
"    <string>Log In</string>\n"
"   </property>\n"
"  </widget>\n"
" </widget>\n"
" <resources/>\n"
"</ui>\n"
"")
        Dialog.setInputMethodHints(QtCore.Qt.ImhNone)
        Dialog.setSizeGripEnabled(False)
        Dialog.setModal(False)
        self.cancel = QtWidgets.QPushButton(Dialog)
        self.cancel.setGeometry(QtCore.QRect(300, 200, 75, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.cancel.setFont(font)
        self.cancel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cancel.setObjectName("cancel")
        self.ok = QtWidgets.QPushButton(Dialog)
        self.ok.setGeometry(QtCore.QRect(214, 200, 75, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.ok.setFont(font)
        self.ok.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ok.setObjectName("ok")
        self.line_new_username = QtWidgets.QLineEdit(Dialog)
        self.line_new_username.setGeometry(QtCore.QRect(90, 58, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.line_new_username.setFont(font)
        self.line_new_username.setMaxLength(10)
        self.line_new_username.setFrame(False)
        self.line_new_username.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.line_new_username.setClearButtonEnabled(True)
        self.line_new_username.setObjectName("line_new_username")
        self.line_password = QtWidgets.QLineEdit(Dialog)
        self.line_password.setGeometry(QtCore.QRect(90, 89, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.line_password.setFont(font)
        self.line_password.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.line_password.setMaxLength(10)
        self.line_password.setFrame(False)
        self.line_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.line_password.setClearButtonEnabled(True)
        self.line_password.setObjectName("line_password")
        self.lbl_warn = QtWidgets.QLabel(Dialog)
        self.lbl_warn.setGeometry(QtCore.QRect(90, 120, 225, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lbl_warn.setFont(font)
        self.lbl_warn.setStyleSheet("color:red;")
        self.lbl_warn.setText("")
        self.lbl_warn.setObjectName("lbl_warn")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Changing Username"))
        self.cancel.setText(_translate("Dialog", "Cancel"))
        self.ok.setText(_translate("Dialog", "OK"))
        self.line_new_username.setPlaceholderText(_translate("Dialog", "new username (min. 5)..."))
        self.line_password.setPlaceholderText(_translate("Dialog", "your password (important)"))
